[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
strict = true
namespace_packages = true
exclude = (^tests/|^workflow_kit/tests/|^examples/)

[mypy.plugins.django-stubs]
django_settings_module = tests.test_project.settings

[mypy.plugins.drf-stubs]
django_settings_module = tests.test_project.settings

[mypy-tests.*]
ignore_errors = True

[mypy-workflow_kit.tests.*]
ignore_errors = True
