# Generated by Django 6.1 on 2026-08-08 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_kit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_approvals', to=settings.AUTH_USER_MODEL)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='workflow_kit.workflowexecution')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['execution', 'status'], name='workflow_ki_executi_38330c_idx'), models.Index(fields=['execution', 'step'], name='workflow_ki_executi_d95089_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('workflow_started', 'Workflow started'), ('transition_executed', 'Transition executed'), ('approval_required', 'Approval required'), ('approval_approved', 'Approval approved'), ('approval_rejected', 'Approval rejected'), ('workflow_completed', 'Workflow completed'), ('workflow_cancelled', 'Workflow cancelled')], db_index=True, max_length=40)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('source_state', models.CharField(blank=True, max_length=100)),
                ('target_state', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workflow_kit.workflowexecution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='workflow_ki_executi_84aac5_idx'), models.Index(fields=['execution', 'event_type'], name='workflow_ki_executi_083576_idx')],
            },
        ),
    ]
