# Generated by Django 6.1 on 2026-08-09 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_kit', '0002_approval_workflowevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='allow_self',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='assignment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approval',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='mode',
            field=models.CharField(choices=[('ALL', 'All'), ('ANY', 'Any'), ('QUORUM', 'Quorum')], db_index=True, default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='approval',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('workflow_started', 'Workflow started'), ('transition_executed', 'Transition executed'), ('approval_required', 'Approval required'), ('approval_approved', 'Approval approved'), ('approval_rejected', 'Approval rejected'), ('approval_cancelled', 'Approval cancelled'), ('approval_escalated', 'Approval escalated'), ('approval_delegated', 'Approval delegated'), ('delegation_revoked', 'Delegation revoked'), ('workflow_completed', 'Workflow completed'), ('workflow_cancelled', 'Workflow cancelled')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='WorkflowDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='workflow_kit.workflowexecution')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wk_delegations', to=settings.AUTH_USER_MODEL)),
                ('granter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_delegations_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to='workflow_kit.workflowdelegation'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['status', 'due_at'], name='workflow_ki_status_f6ca3e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['execution', 'active'], name='workflow_ki_executi_d70fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowdelegation',
            index=models.Index(fields=['grantee', 'active'], name='workflow_ki_grantee_4011ef_idx'),
        ),
    ]
