# Generated by Django 6.1 on 2026-08-09 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bind_existing_executions(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    """Pin every existing execution to a version snapshot (Phase 9 upgrade).

    For each workflow identity with executions it reconstructs version 1 from
    the currently registered definition. If a definition cannot be rebuilt
    safely (unregistered, or using non-serializable elements), the migration
    raises instead of inventing historical data.
    """
    from django.utils import timezone

    WorkflowVersion = apps.get_model("workflow_kit", "WorkflowVersion")
    WorkflowExecution = apps.get_model("workflow_kit", "WorkflowExecution")
    names = sorted(
        WorkflowExecution.objects.values_list("workflow_name", flat=True).distinct()
    )
    if not names:
        return

    from workflow_kit.engine.registry import get_workflow
    from workflow_kit.engine.versioning import serialize_workflow
    from workflow_kit.exceptions import WorkflowNotFoundError, WorkflowVersionError

    for name in names:
        try:
            workflow = get_workflow(name)
            snapshot = serialize_workflow(workflow)
        except (WorkflowNotFoundError, WorkflowVersionError) as exc:
            raise RuntimeError(
                "Phase 9 upgrade cannot reconstruct the definition of workflow "
                f"'{name}', which has existing executions. Stop and migrate "
                "manually: register a serializable workflow (built-in conditions, "
                "string permissions, string approvers) for every workflow with "
                "executions before applying this migration. Refusing to invent a "
                "definition snapshot for historical executions."
            ) from exc

        version = WorkflowVersion.objects.filter(workflow=name, version=1).first()
        if version is None:
            version = WorkflowVersion.objects.create(
                workflow=name,
                version=1,
                status="PUBLISHED",
                definition=snapshot,
                changelog="Initial version (created during Phase 9 upgrade).",
                published_at=timezone.now(),
            )
        WorkflowExecution.objects.filter(workflow_name=name).update(workflow_version=version)


def reverse_bind(apps, schema_editor) -> None:  # type: ignore[no-untyped-def]
    WorkflowExecution = apps.get_model("workflow_kit", "WorkflowExecution")
    WorkflowExecution.objects.update(workflow_version=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_kit', '0003_approval_allow_self_approval_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(db_index=True, max_length=200)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], db_index=True, default='DRAFT', max_length=20)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_created_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow', '-version'],
            },
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='workflow_kit.workflowversion'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['workflow_name', 'workflow_version'], name='workflow_ki_workflo_f618d4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'status'], name='workflow_ki_workflo_0e8451_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', '-version'], name='workflow_ki_workflo_0c634e_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='unique_version_per_workflow'),
        ),
        migrations.RunPython(bind_existing_executions, reverse_bind),
    ]
