# Generated by Django 6.1 on 2026-08-09 18:27

import django.db.models.deletion
import workflow_kit.models.attachment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_kit', '0004_workflowversion_workflowexecution_workflow_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowevent',
            name='event_type',
            field=models.CharField(choices=[('workflow_started', 'Workflow started'), ('transition_executed', 'Transition executed'), ('approval_required', 'Approval required'), ('approval_approved', 'Approval approved'), ('approval_rejected', 'Approval rejected'), ('approval_cancelled', 'Approval cancelled'), ('approval_escalated', 'Approval escalated'), ('approval_delegated', 'Approval delegated'), ('delegation_revoked', 'Delegation revoked'), ('comment_added', 'Comment added'), ('attachment_added', 'Attachment added'), ('workflow_completed', 'Workflow completed'), ('workflow_cancelled', 'Workflow cancelled')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='WorkflowAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=workflow_kit.models.attachment.attachment_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workflow_kit.workflowexecution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='workflow_ki_executi_ee57a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workflow_kit.workflowexecution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wk_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['execution', '-created_at'], name='workflow_ki_executi_f2f613_idx')],
            },
        ),
    ]
