# Generated by Django 6.1 on 2026-08-11 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_kit', '0005_alter_workflowevent_event_type_workflowattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['current_state'], name='workflow_ki_current_087898_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowexecution',
            index=models.Index(fields=['-started_at'], name='workflow_ki_started_152542_idx'),
        ),
    ]
